### ISSUE TITLE
Unclear license of shipped OAuth libraries

### ISSUE THREAD

**Issue by mudrd8mz** [iandavidwild/moodle-auth_wordpress#7]
The files BasicOAuth.php and OAuth.php seem to be a third party libraries. There is no licensing information available for them (sorry if it is somewhere and I missed it). To make sure the inclusion of these libraries is legal as per GPL, please check https://docs.moodle.org/dev/Plugin_contribution_checklist#Licensing and make use of the thirdpartylibs.xml file.

**Comment by iandavidwild** [comment]
The relevant licensing information has now been added.
